# /apps/blog.silarhi.fr/docker-compose.yml
version: '3'

services:
  app:
    image: php:7.4-apache
    container_name: ${NAME}
    build: .
    #ports:
    #  - "8888:80"
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${NAME}.rule=Host(`${NAME}.jrcandev.netlib.re`)"
      - "traefik.http.routers.${NAME}.entrypoints=websecure"
      - "traefik.http.routers.${NAME}.tls.certresolver=lets-encrypt"
    restart: always

volumes:
  content:

    null
networks:
  web:
    external: true
